services:
  front:
    build:
      context: .
    ports:
      - 5173:5173
    volumes:
      - '.:/nlw-agents-class-front'
    command: bash start.sh
    networks:
      - nlw-agents-class-net

networks:
  nlw-agents-class-net:
    name: nlw-agents-class-net
    external: true
